name: loggy
description: Log your day, everyday.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  json_annotation: ^4.9.0
  meta: ^1.8.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.0.5
  json_serializable: ^6.8.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

icons_launcher:
  image_path: 'assets/icon.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    web:
      enable: true
    linux:
      enable: true
