name: loggy
description: Log your day, everyday.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
