// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbb7Kjl9CWvpaqOg_B8YezTou4M0Pr8JM',
    appId: '1:682288113146:web:e344f3fd5918e4091a3043',
    messagingSenderId: '682288113146',
    projectId: 'loggy-fa4ba',
    authDomain: 'loggy-fa4ba.firebaseapp.com',
    storageBucket: 'loggy-fa4ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGU05jmFyXruMYJOBjca2AGb9m6Bo1_Fc',
    appId: '1:682288113146:android:0cd05e8c01b52d981a3043',
    messagingSenderId: '682288113146',
    projectId: 'loggy-fa4ba',
    storageBucket: 'loggy-fa4ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtLQ4XRA1AB7OwwUdJnyu81CFqezxnzck',
    appId: '1:682288113146:ios:a6ab69572dddfd321a3043',
    messagingSenderId: '682288113146',
    projectId: 'loggy-fa4ba',
    storageBucket: 'loggy-fa4ba.appspot.com',
    iosClientId: '682288113146-1rq864qnhjlei236njks1hkt0k0hd4o2.apps.googleusercontent.com',
    iosBundleId: 'com.draco.loggy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtLQ4XRA1AB7OwwUdJnyu81CFqezxnzck',
    appId: '1:682288113146:ios:a6ab69572dddfd321a3043',
    messagingSenderId: '682288113146',
    projectId: 'loggy-fa4ba',
    storageBucket: 'loggy-fa4ba.appspot.com',
    iosClientId: '682288113146-1rq864qnhjlei236njks1hkt0k0hd4o2.apps.googleusercontent.com',
    iosBundleId: 'com.draco.loggy',
  );
}
